### ISSUE TITLE
Downloadable files miss information?

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/wikipathways-issue-tracker#2]
Hi everyone,

For this [pathway](http://www.wikipathways.org/index.php/Pathway:WP2826#nogo2) the bottom arrow is missing when I download the png or pdf file.
Upon accessing the pathway, the bottom arrow is not displayed as well ( I needed to zoom out 1 time for that).
I do not know what is causing this, however it does not improve the user friendliness of wikipathways

**Comment by AlexanderPico** [comment]
I fixed it by making adjustments to the layout. The issue is that the "visible area" determined by the software only considers nodes and end points. So, the path of the edge was outside of that area.
