### ISSUE TITLE
Visualization WikiPathways and Pathvisio are different

### ISSUE THREAD

**Issue by marvinm2** [wikipathways/wikipathways-issue-tracker#5]
Hey!

Jacco, an intern, made a picture in Pathvisio for his thesis, with a lot of effort in making it visually appealing. When he recently uploaded to WikiPathways, a couple of things are different. Why does WikiPathways read the file differently when compared to Pathvisio? Shapes shift places, coloring differs, layer-order differs. 

This is the pathway that I talk about:
http://wikipathways.org/index.php/Pathway:WP4030

It is not the most important thing, but would be nice to have consistency between the Pathvisio and WikiPathways.org. 

Kind regards,
Marvin

**Comment by AlexanderPico** [comment]
The difference is Java vs JavaScript... and all the libraries that are specific to each technology. These are completely different code bases and near impossible to get 100% identical.

However, they are both open source projects, so if there are particular differences you want to try to fix, we can help by pointing out where in the code to try making changes.
