### ISSUE TITLE
Pathway arrows or lines that do not need to be connected

### ISSUE THREAD

**Issue by marvinm2** [wikipathways/wikipathways-issue-tracker#6]
There are many Pathways that have the tag to 'Fix interactions'. In many cases, these are indeed simple mistakes and can be resolved by proper connecting, but sometimes you do not want to connect an arrow. 

There are many approved pathways in WikiPathways that still have this tag, sometimes pointing towards arrows or lines that are not meant to be connected. Wouldn't it be an option to have the possibility to ignore this tag for those specific arrows that are not meant to be connected?

I see that one pathway, that was made with arrows that shouldn't be connected, used invisible label nodes to connect them. That is an option, but not the right one. http://wikipathways.org/index.php/Pathway:WP4030

What to do about this minor thing?

**Comment by mkutmon** [comment]
Please use the GraphicalLine for lines that are not intended to connect something. This was introduced for exactly this purpose! In PathVisio you can use the TypeConverter plugin to convert Interactions into GraphicalLines if needed

**Comment by marvinm2** [comment]
Okay, thank you for telling. It seems that not a lot of people (one of which was me, of course) know about the difference between a normal line and a graphical line. This can be closed for me now.
